Repository zsmartsystems/com.zsmartsystems.zigbee, pull requests merged in 2020-04, with the labels that each got.

#1025 Updated install code handling for Ember ZNet 6.7+ (EZSP8+)
  com.zsmartsystems.zigbee.console.ember/src/main/java/com/zsmartsystems/zigbee/console/ember/EmberConsoleSecurityStateCommand.java
  com.zsmartsystems.zigbee.console.main/src/main/java/com/zsmartsystems/zigbee/console/main/ZigBeeConsole.java
  com.zsmartsystems.zigbee.console/src/main/java/com/zsmartsystems/zigbee/console/ZigBeeConsoleInstallKeyCommand.java
  com.zsmartsystems.zigbee.console/src/main/java/com/zsmartsystems/zigbee/console/ZigBeeConsoleTrustCentreCommand.java
  com.zsmartsystems.zigbee.dongle.ember/src/main/java/com/zsmartsystems/zigbee/dongle/ember/EmberNcp.java
  com.zsmartsystems.zigbee.dongle.ember/src/main/java/com/zsmartsystems/zigbee/dongle/ember/ZigBeeDongleEzsp.java
  com.zsmartsystems.zigbee.dongle.ember/src/test/java/com/zsmartsystems/zigbee/dongle/ember/ZigBeeDongleEzspTest.java
  com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/transport/TrustCentreJoinMode.java
Labels: EMBER

#1030 Fix test failure introduced in IAS Zone Change #1023
  com.zsmartsystems.zigbee/src/test/java/com/zsmartsystems/zigbee/app/iasclient/ZclIasZoneClientTest.java
Labels: bug

#1032 Add GenericDeviceTypeEnum
  com.zsmartsystems.zigbee.autocode/src/main/resources/0000_Basic.xml
  com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/basic/GenericDeviceTypeEnum.java
  com.zsmartsystems.zigbee/src/test/java/com/zsmartsystems/zigbee/zcl/clusters/basic/GenericDeviceTypeEnumTest.java
Labels: enhancement

#1037 Fix autocoder array count generator
  com.zsmartsystems.zigbee.autocode/src/main/java/com/zsmartsystems/zigbee/autocode/ZigBeeZclClusterGenerator.java
  com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/ZclMeteringCluster.java
  com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/ZclPriceCluster.java
Labels: bug

#1033 Ember: Handling of ASH NAK rejection condition
  com.zsmartsystems.zigbee.dongle.ember/src/main/java/com/zsmartsystems/zigbee/dongle/ember/internal/ash/AshFrameHandler.java
Labels: bug

#1036 Fix error message in Telegesis command handler
  com.zsmartsystems.zigbee.console.ember/src/main/java/com/zsmartsystems/zigbee/console/ember/EmberConsoleAbstractCommand.java
  com.zsmartsystems.zigbee.console.telegesis/src/main/java/com/zsmartsystems/zigbee/console/telegesis/TelegesisConsoleAbstractCommand.java
Labels: EMBER, TELEGESIS

#1041 ezsp - add support for custom frames
  com.zsmartsystems.zigbee.dongle.ember.autocode/src/main/resources/ezsp_protocol.xml
  com.zsmartsystems.zigbee.dongle.ember/src/main/java/com/zsmartsystems/zigbee/dongle/ember/ezsp/EzspFrame.java
  com.zsmartsystems.zigbee.dongle.ember/src/main/java/com/zsmartsystems/zigbee/dongle/ember/ezsp/command/EzspCustomFrameHandler.java
  com.zsmartsystems.zigbee.dongle.ember/src/main/java/com/zsmartsystems/zigbee/dongle/ember/ezsp/command/EzspCustomFrameRequest.java
  com.zsmartsystems.zigbee.dongle.ember/src/main/java/com/zsmartsystems/zigbee/dongle/ember/ezsp/command/EzspCustomFrameResponse.java
Labels: EMBER
